# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [12.x, 14.x, 16.x]
  #       # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: "npm"
  #     - run: npm ci
  #     - run: npm run lint
  #     - run: npm run test:local
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 设置 ssh key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.RSA}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "${{secrets.SERVER_IP}}" >> ~/.ssh/known_hosts
      - name: 登录服务器 && 拉项目
        run: |
          ssh root@${{secrets.SERVER_IP}} "
          cd /home/task
          rm -rf owner-server
          git clone git@github.com:MonsterXiong/owner-server.git
          cd owner-server
          git pull origin master
          git remote remove origin
          docker build -t owner-server .
          docker run -p 4007:3000 -d --name server owner-server
          "
      # git remote add origin https://MonsterXiong:${{secrets.PASSWORD}}@github.com/owner-server.git
      # docker stop server && docker rm server && docker rmi owner-server
        
      - name: 什么位置
        run: pwd
      - name: 删除 ssh key
        run: rm -rf ~/.ssh/id_rsa
