# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - "dev"
    paths:
      - ".github/workflows/*"
      # - '__test__/**' # dev 不需要立即测试
      - "src/**"
      - "Dockerfile"
      - "docker-compose.yml"
      - "bin/*"

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 设置 ssh key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.RSA}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "${{secrets.SERVER_IP}}" >> ~/.ssh/known_hosts
      - name: 登录服务器 && 拉项目
        run: |
          ssh root@${{secrets.SERVER_IP}} "
          cd /home/task
          rm -rf owner-server
          git clone git@github.com:MonsterXiong/owner-server.git
          cd owner-server
          git checkout dev;
          git pull origin dev
          git remote remove origin
          docker-compose build owner-server
          docker-compose up -d
          "
      # git remote add origin https://MonsterXiong:${{secrets.PASSWORD}}@github.com/owner-server.git
      #
      - name: 删除 ssh key
        run: rm -rf ~/.ssh/id_rsa
